---
title: "README"
format: html
editor: visual
---

## Maize

```{r}

#snpurl <- "https://github.com/EEOB-BioData/BCB546_Spring2024/blob/29fc8f45a1f28a1376e62ef5fceff9b99cb409d3/assignments/UNIX_Assignment/snp_position.txt"

library(tidyverse)
library(tidyr)
library(data.table)
library(dplyr)

snp <- read_tsv("snp_position.txt")
snp_f <- arrange(snp[c(1,3,4)], SNP_ID)

fang <- read_tsv("fang_et_al_genotypes.txt")

maize <- filter(fang, startsWith(Group, 'ZMM')) #filter needs boolean in second arg

maize_t <- transpose(maize)
rownames(maize_t) <- colnames(maize)
colnames(maize_t) <- rownames(maize)
setDT(maize_t, keep.rownames = TRUE)
colnames(maize_t)[colnames(maize_t) == 'rn'] <- 'SNP_ID'

maize_snp <- merge(snp_f, maize_t, by = 'SNP_ID')


for(i in 1:10) {
  maize_inc <- arrange(filter(maize_snp, Chromosome == i), Position)
  write_tsv(maize_inc, sprintf("maize_inc_%d.txt",i))
}


for(i in 1:10) {
  maize_de <- arrange(filter(maize_snp, Chromosome == i), desc(Position))
  maize_de[maize_de == '?/?'] <- '-/-'
  maize_dec <- maize_de
  write_tsv(maize_dec, sprintf("maize_dec_%d.txt",i))
}

maize_unknowns <- filter(maize_snp, Chromosome == "unknown")
write_tsv(maize_unknowns, "maize_unknown.txt")

maize_multiples <- filter(maize_snp, Chromosome =="multiple")
write_tsv(maize_multiples, "maize_multiple.txt")

```

## Teosinte

```{r}

```
